### ISSUE TITLE
add JSON/XML files previewer

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-previewer#18]
Add support for pretty-printing of common text formats, e.g. XML, JSON. Perhaps also simple syntax coloring ?

- [ ] JSON pretty-printer
- [ ] XML pretty-printer

**Comment by jirikuncar** [comment]
Shall we use any of following syntax highlighters or simple `<pre/>` is enough?

- http://prismjs.com/
- https://highlightjs.org/
- other?

**Comment by krzysztof** [comment]
I was going to suggest highlightsjs.org. A nice to have would be previewing of files inside a zip-ball ;)
