### ISSUE TITLE
extensions: image previewer

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-previewer#22]
- Previewer for standard image formats such as png, jpg, tiff.
- Simple previewer should ensure not load files over a given size.
- More advanced previewer should use Flask-IIIF

Via zenodo/zenodo#155

**Comment by egabancho** [comment]
cc @drjova

**Comment by lnielsen** [comment]
FYI we're starting with just a simple previewer for small file sizes.
