### ISSUE TITLE
tests: KeyError: 'recid' in tests/test_macros.py

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-previewer#31]
- https://travis-ci.org/inveniosoftware/invenio-previewer/jobs/125494640
- use `recid_minter` and "control_number" key instead "recid" ...

**Comment by slint** [comment]
Seems like [record key aliases removal](https://github.com/inveniosoftware/invenio-records/commit/e2473b13427e0a5c2d14e96196ff52e71d872d95#diff-2d73cb6cf17db92f25fd968101bec4b2L37) breaks the [record creation](https://github.com/inveniosoftware/invenio-previewer/blob/master/tests/conftest.py#L166) test fixture.
