### ISSUE TITLE
Unable to create the application example

### ISSUE THREAD

**Issue by targos** [inveniosoftware/invenio-previewer#67]
I am trying to follow the guide at https://github.com/inveniosoftware/invenio-previewer/blob/master/examples/app.py

After fixing a missing dependency (https://github.com/inveniosoftware/invenio-previewer/pull/66), I have the following error at step 6 (`FLASK_APP=app.py flask assets build`):
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/mzasso/git/forks/invenio-previewer/examples/static/js/invenio_i18n/angularLangSelector.js'
```

**Comment by drjova** [comment]
@targos try to include the following to the app.py

```python
from invenio_i18n import InvenioI18N

Babel(app)
InvenioI18N(app) # Initialize Invenio18N
InvenioAccounts(app)
```

and then run

```
$ flask collect
$ flask assets build
```

if it works for you could you please make a PR?

**Comment by targos** [comment]
https://github.com/inveniosoftware/invenio-previewer/pull/69
