### ISSUE TITLE
zip: use the `allowZip64` parameter for files over 4GB

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-previewer#72]
Preview of Zipfiles larger that 2GB is not supported at the moment. Passing the `allowZip64` flag, would make this possible, though it's not clear from Python's [`zipfile` docs](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile) if there are complications.

**Comment by equadon** [comment]
The `allowZip64` parameter only affect writing zip files so previewing large files (at least locally) works without any issues.

The complications mentioned in the [`zipfile` docs](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile) seem to be related to the InfoZip utilities not supporting the Zip64 extension but support was added 9 years ago so it shouldn't cause any issues now.
