### ISSUE TITLE
ispy: preview CMS event files

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-previewer#74]
For CERN Open Data based on Invenio 2, the CMS event display files attached tp records were previewed using a dedicated package https://github.com/inveniosoftware/invenio-previewer-ispy

For CERN Open Data based on Invenio 3, it would be good to port the facility to preview `ispy` files directly in this package.

Note that doing this may require to put `ispy-webgl` on npm; to be checked with Tom.

It would be good to add a small test case file, etc as usual.

**Comment by lnielsen** [comment]
Is it not better suited in a separate package since I imagine it has a very small user base?

**Comment by tiborsimko** [comment]
@lnielsen If it's not easy to make things nicely optional (kind of like `pip install invenio-previewer[csv,pdf,ispy,opera]`) due to asset management, then OK for moving it out.  

@ioannistsanaktsidis We can maybe start by implementing the previewer directly within the COD3 overlay, in this way we can use the EOS files directly without "lazy" invenio-recods-files? Let's see IRL?

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko ok lets discuss this today IRL. I guess there is no big deal to implement it as a COD3 module directly.
