### ISSUE TITLE
demobbed: preview OPERA event files

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-previewer#75]
Integrate OPERA previewer https://github.com/dmitr25/demobbed-viewer enabling to preview OPERA event files.

We have been given green liight by Sergey to also make an npm release of the previewer.

The name "demobbed" is not so nice, but there were no other proposals...

Note that the JS sources contain data bundled in, while ideally the previewer should read the data from record files, once OPERA data are published. 

Example: http://opendatadev.cern.ch/record/4002

**Comment by lnielsen** [comment]
Same as for #74, is it not better suited in a separate package since I imagine it has a very small user base? E.g. invenio-previewer-hep or similar?

**Comment by tiborsimko** [comment]
Yes, we went for the overlay at the end. Closing the issue.
