### ISSUE TITLE
global: license change implementation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-previewer#79]
Related to inveniosoftware/invenio#3829

- [x] Confirm license change with non-CERN contributors
- [x] Review module for GPL dependencies
- [x] Run license change scripts

**Comment by equadon** [comment]
Is the GPL dependency in docutils an issue?
`docutils    0.14    public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)`
From COPYING.txt:
```
* tools/editors/emacs/rst.el, copyright by Free Software Foundation,
  Inc., released under the `GNU General Public License`_ version 3 or
later (`local copy`__).
```

**Comment by lnielsen** [comment]
No shouldn't be an issue since we're not having any imports from docutils, we're just using it as part of sphinx.
