### ISSUE TITLE
assets: PDFView is not defined

### ISSUE THREAD

**Issue by miltalex** [inveniosoftware/invenio-previewer#95]
After I updated to invenio-previewer==1.0.0a12, when I try to preview a pdf file, I get the following console error : 

``` Uncaught ReferenceError: PDFView is not defined. ```

I get the error [here](https://github.com/inveniosoftware/invenio-previewer/blob/17e1bfb7823362527d2051f80c17385bb690de4c/invenio_previewer/templates/invenio_previewer/pdfjs.html#L312).

I think   ``` window.PDFView = PDFViewerApplication; ```  in [/assets/js/pdfjs/viewer.js](https://github.com/inveniosoftware/invenio-previewer/blob/e06483cf270dbddf1012b4bc0a6792231fe47f4f/invenio_previewer/assets/js/pdfjs/viewer.js#L7098), doesn't load in pdfjs.html as it should.

**Comment by ntarocco** [comment]
Thank you for reporting this! :)
@lnielsen I have added to the sprint, I guess we should fix this before release.

**Comment by roksys** [comment]
@miltalex, could you confirm that PDF previewer works now?

**Comment by miltalex** [comment]
@roksys It works :)
